import React from 'react';
import { ExternalLink, ShoppingBag } from 'lucide-react';

// Preserve the Special Links generated by the account owner, including tracking.
const amazonLinks = [
  { href: 'https://amzn.to/3TgaVKL', title: 'Raquete de beach tennis Adidas' },
  { href: 'https://amzn.to/4rucOzZ', title: 'Mouse pad gamer Fortrek MPG-103' },
];

export const AmazonAffiliateAds: React.FC = () => (
  <aside
    aria-labelledby="amazon-ad-heading"
    aria-describedby="amazon-affiliate-disclosure"
    className="mx-auto mt-12 w-full max-w-3xl rounded-2xl border border-slate-700 bg-slate-900 p-5 sm:p-6"
  >
    <p className="text-xs font-bold uppercase tracking-widest text-amber-300">Publicidade</p>
    <h2 id="amazon-ad-heading" className="mt-2 text-xl font-bold text-white">
      Confira na Amazon
    </h2>
    <p id="amazon-affiliate-disclosure" className="mt-3 text-sm leading-relaxed text-slate-300">
      Como participante do Programa de Associados da Amazon, sou remunerado pelas compras qualificadas efetuadas.
    </p>

    <div className="mt-5 grid gap-4 sm:grid-cols-2">
      {amazonLinks.map(({ href, title }) => (
        <div key={href} className="flex flex-col rounded-xl border border-slate-700 bg-slate-950 p-5">
          <ShoppingBag size={24} aria-hidden="true" className="mb-3 text-amber-300" />
          <h3 className="text-base font-semibold text-white">{title}</h3>
          <p className="mb-4 mt-2 text-sm leading-relaxed text-slate-400">
            Consulte os detalhes e as condições de compra na Amazon.
          </p>
          <p className="mb-2 mt-auto text-xs font-medium text-amber-200">Publicidade · Link de afiliado</p>
          <a
            href={href}
            target="_blank"
            rel="sponsored nofollow noopener"
            aria-label={`Ver na Amazon: ${title} (link de afiliado, abre em nova aba)`}
            className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-amber-300 px-4 py-3 text-sm font-bold text-slate-950 transition-colors hover:bg-amber-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-amber-300"
          >
            Ver na Amazon
            <ExternalLink size={16} aria-hidden="true" />
          </a>
          <span className="mt-2 text-xs text-slate-400">Abre em nova aba</span>
        </div>
      ))}
    </div>
    <p className="mt-4 text-xs leading-relaxed text-slate-400">
      Ao acessar os links, a Amazon poderá usar cookies e outras tecnologias para atribuir compras ao associado,
      conforme sua{' '}
      <a className="underline underline-offset-2 hover:text-white" href="https://www.amazon.com.br/gp/help/customer/display.html?nodeId=GX7NJQ4ZB8MHFRNJ">
        Notificação de Privacidade
      </a>.
    </p>
  </aside>
);
